wallpaper {
    monitor = DP-2
    path = /home/artemis/Wallpapers/m.jpg
    fit_mode = cover
}

wallpaper {
    monitor = DP-3
    path = /home/artemis/Wallpapers/m.jpg
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-1
    path = /home/artemis/Wallpapers/m.jpg
    fit_mode = cover
}

# optional fallback (good practice)
wallpaper {
    monitor =
    path = /home/artemis/Wallpapers/m.jpg
    fit_mode = cover
}

splash = false
